export const authActionTypes = {
    SEND_LOGIN_REQUEST: 'SEND_LOGIN_REQUEST',
    SEND_LOGIN_SUCCESS: 'SEND_LOGIN_SUCCESS',
    SEND_LOGIN_FAILURE: 'SEND_LOGIN_FAILURE',

    SEND_SIGNUP_REQUEST: 'SEND_SIGNUP_REQUEST',
    SEND_SIGNUP_SUCCESS: 'SEND_SIGNUP_SUCCESS',
    SEND_SIGNUP_FAILURE: 'SEND_SIGNUP_FAILURE',

    TOGGLE_SHOW_LOGIN_FORM: 'TOGGLE_SHOW_LOGIN_FORM',
    LOGOUT: 'LOGOUT',
}