export const productsActionTypes = {
    GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
    GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
    GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",

    SET_PRODUCT_DETAILS: "SET_PRODUCT_DETAILS",

    ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
    INCREASE_PRODUCT_QUANTITY: "INCREASE_PRODUCT_QUANTITY",
    DECREASE_PRODUCT_QUANTITY: "DECREASE_PRODUCT_QUANTITY",
    REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
};